### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by robertsolorzano** [robertsolorzano/TranslateMe#1]
Need to create HTML

**Comment by 0304ajay** [comment]
Hello can you describe the issue

**Comment by robertsolorzano** [comment]
Well the issue is almost closed out. Just needed to make basic HTML with search bar text box for translator. You are interested in this project?

**Comment by 0304ajay** [comment]
yes I am interested in doing projects

**Comment by robertsolorzano** [comment]
Issue closed
